package mx.gob.segob.nsjp.ws.cliente.consultaraudiencia;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-05-09T18:17:07.848-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "ConsultarAudienciasByFechasYEstatusExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface ConsultarAudienciasByFechasYEstatusExporter {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/ConsultarAudienciasByFechasYEstatusExporter/consultarAudienciasByFechasYEstatusRequest", output = "http://ws.service.nsjp.segob.gob.mx/ConsultarAudienciasByFechasYEstatusExporter/consultarAudienciasByFechasYEstatusResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/ConsultarAudienciasByFechasYEstatusExporter/consultarAudienciasByFechasYEstatus/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "consultarAudienciasByFechasYEstatus", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.ConsultarAudienciasByFechasYEstatus")
    @WebMethod
    @ResponseWrapper(localName = "consultarAudienciasByFechasYEstatusResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.ConsultarAudienciasByFechasYEstatusResponse")
    public java.util.List<mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.AudienciaDefensoriaWSDTO> consultarAudienciasByFechasYEstatus(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.AudienciaDefensoriaWSDTO arg0
    ) throws NSJPNegocioException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.service.nsjp.segob.gob.mx/ConsultarAudienciasByFechasYEstatusExporter/consultarAudienciaByIdRequest", output = "http://ws.service.nsjp.segob.gob.mx/ConsultarAudienciasByFechasYEstatusExporter/consultarAudienciaByIdResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/ConsultarAudienciasByFechasYEstatusExporter/consultarAudienciaById/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "consultarAudienciaById", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.ConsultarAudienciaById")
    @WebMethod
    @ResponseWrapper(localName = "consultarAudienciaByIdResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.ConsultarAudienciaByIdResponse")
    public mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.AudienciaDefensoriaWSDTO consultarAudienciaById(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.AudienciaDefensoriaWSDTO arg0
    ) throws NSJPNegocioException_Exception;
}
