package mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2012-05-07T19:17:49.997-05:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "PrincipalSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface PrincipalSoap {

    /**
     * Consulta una audiencia y los resolutivos.
     */
    @WebResult(name = "consultar_ResolutivosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "consultar_Resolutivos", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.ConsultarResolutivos")
    @WebMethod(operationName = "consultar_Resolutivos", action = "http://tempuri.org/consultar_Resolutivos")
    @ResponseWrapper(localName = "consultar_ResolutivosResponse", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.ConsultarResolutivosResponse")
    public int consultarResolutivos(
        @WebParam(name = "S_Audiencia", targetNamespace = "http://tempuri.org/")
        java.lang.String sAudiencia,
        @WebParam(name = "S_Usuario", targetNamespace = "http://tempuri.org/")
        java.lang.String sUsuario
    );

    /**
     * Agenda una audiencia, y devuelve un identificador sobre el estado.
     */
    @WebResult(name = "agendar_AudienciaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "agendar_Audiencia", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.AgendarAudiencia")
    @WebMethod(operationName = "agendar_Audiencia", action = "http://tempuri.org/agendar_Audiencia")
    @ResponseWrapper(localName = "agendar_AudienciaResponse", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.AgendarAudienciaResponse")
    public int agendarAudiencia(
        @WebParam(name = "S_Audiencia", targetNamespace = "http://tempuri.org/")
        java.lang.String sAudiencia,
        @WebParam(name = "S_Usuario", targetNamespace = "http://tempuri.org/")
        java.lang.String sUsuario
    );

    /**
     * Método realizado para saber el estado de una audiencia.
     */
    @WebResult(name = "estado_AudienciaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "estado_Audiencia", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.EstadoAudiencia")
    @WebMethod(operationName = "estado_Audiencia", action = "http://tempuri.org/estado_Audiencia")
    @ResponseWrapper(localName = "estado_AudienciaResponse", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.EstadoAudienciaResponse")
    public int estadoAudiencia(
        @WebParam(name = "S_Audiencia", targetNamespace = "http://tempuri.org/")
        java.lang.String sAudiencia,
        @WebParam(name = "S_Usuario", targetNamespace = "http://tempuri.org/")
        java.lang.String sUsuario
    );

    /**
     * Consulta los videos de la audiencia y genera el listado de archivos a transferir.
     */
    @WebResult(name = "ligas_SFTPResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ligas_SFTP", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.LigasSFTP")
    @WebMethod(operationName = "ligas_SFTP", action = "http://tempuri.org/ligas_SFTP")
    @ResponseWrapper(localName = "ligas_SFTPResponse", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.LigasSFTPResponse")
    public int ligasSFTP(
        @WebParam(name = "S_Audiencia", targetNamespace = "http://tempuri.org/")
        java.lang.String sAudiencia,
        @WebParam(name = "S_Usuario", targetNamespace = "http://tempuri.org/")
        java.lang.String sUsuario,
        @WebParam(name = "L_Usuario", targetNamespace = "http://tempuri.org/")
        long lUsuario
    );

    /**
     * Consulta una audiencia y resolutivos, transfiere los archivos de grabación si la audiencia ha finalizado.
     */
    @WebResult(name = "consultar_AudienciaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "consultar_Audiencia", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.ConsultarAudiencia")
    @WebMethod(operationName = "consultar_Audiencia", action = "http://tempuri.org/consultar_Audiencia")
    @ResponseWrapper(localName = "consultar_AudienciaResponse", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.ConsultarAudienciaResponse")
    public int consultarAudiencia(
        @WebParam(name = "S_Audiencia", targetNamespace = "http://tempuri.org/")
        java.lang.String sAudiencia,
        @WebParam(name = "S_Usuario", targetNamespace = "http://tempuri.org/")
        java.lang.String sUsuario
    );

    /**
     * Elimina todas las audiencias que compartan el ID 'audiencia_ID', y devuelve un identificador sobre el estado.
     */
    @WebResult(name = "eliminar_AudienciaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "eliminar_Audiencia", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.EliminarAudiencia")
    @WebMethod(operationName = "eliminar_Audiencia", action = "http://tempuri.org/eliminar_Audiencia")
    @ResponseWrapper(localName = "eliminar_AudienciaResponse", targetNamespace = "http://tempuri.org/", className = "mx.gob.segob.nsjp.ws.cliente.agendaraudienciajavs.EliminarAudienciaResponse")
    public int eliminarAudiencia(
        @WebParam(name = "S_Audiencia", targetNamespace = "http://tempuri.org/")
        java.lang.String sAudiencia,
        @WebParam(name = "S_Usuario", targetNamespace = "http://tempuri.org/")
        java.lang.String sUsuario
    );
}
